"""
Events Module
=============

Responsibility:
    - Define the standard objects passed between Engine, Strategy, Portfolio, and Execution.
"""

from dataclasses import dataclass
from typing import Optional
from datetime import datetime

@dataclass
class Event:
    """Base class for all events."""
    pass

@dataclass
class MarketEvent(Event):
    """
    Triggered when new data is available.
    """
    time: datetime

@dataclass
class SignalEvent(Event):
    """
    Generated by the Strategy. "I want to trade this."
    """
    symbol: str
    datetime: datetime
    signal_type: str  # "LONG" or "SHORT"
    strength: float = 1.0  # 1.0 = Max Conviction

@dataclass
class OrderEvent(Event):
    """
    Generated by the Risk Manager. "Broker, execute this."
    """
    symbol: str
    quantity: float  # + for Buy, - for Sell
    order_type: str = "MARKET" # MARKET, LIMIT
    price: Optional[float] = None # Required for LIMIT
    meta: Optional[dict] = None  # Holds Option details (strike, expiry)

@dataclass
class FillEvent(Event):
    """
    Generated by Execution Handler. "Trade confirmed."
    """
    datetime: datetime
    symbol: str
    quantity: float
    fill_price: float
    commission: float
    exchange: str = "SIMULATED"
    meta: Optional[dict] = None # Holds Option details